export var VENDOR = {
  firstName: "",
  middleName: "",
  lastName: "",
  contactPerson: "",
  contactPersonPhone: "",
  street: "",
  city: "",
  province: "",
  zipCode: "",
  country: "",
  TIN: "",
  businessType: null,
  paymentTerms: "",
  paymentMethod: null,
  productServicesProvided: "",
  contractStart: "",
  contractEnd: "",
  billingAddress1: "",
  billingAddress2: "",
  rating: "",
  notes: "",
  dateCreated: "",
};
